site_name: CountLog
repo_name: 'craigcarr/CountLog'
repo_url: 'https://github.com/craigcarr/CountLog'

markdown_extensions:
  - admonition

theme:
  name: material
  palette:
    primary: 'green'
    accent: 'green'
  logo: 'logo192.png'

google_analytics:
  - 'UA-154365911-1'
  - 'auto'

nav:
  - Home: index.md
  - Use Cases: usecases.md
  - Alternatives: alternatives.md
  - Installation: installation.md
